apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-operator-mariadb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mariadb-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - post
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mariadb-role
subjects:
  # Applying the role to both SA (with and without prefix) to be able
  # to run the operator local
- kind: ServiceAccount
  name: mariadb-operator-mariadb
  namespace: openstack
- kind: ServiceAccount
  name: mariadb
  namespace: openstack
